# Visit https://foundry-rs.github.io/starknet-foundry/appendix/snfoundry-toml.html
# and https://foundry-rs.github.io/starknet-foundry/projects/configuration.html for more information

[sncast.devnet]
url = "http://127.0.0.1:5050"
account = "devnet_account"
accounts-file = "accounts.json"
